package com.qdong.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.qdong.greendao.User;
import com.qdong.greendao.MqttChatEntity;

import com.qdong.greendao.UserDao;
import com.qdong.greendao.MqttChatEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig mqttChatEntityDaoConfig;

    private final UserDao userDao;
    private final MqttChatEntityDao mqttChatEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        mqttChatEntityDaoConfig = daoConfigMap.get(MqttChatEntityDao.class).clone();
        mqttChatEntityDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        mqttChatEntityDao = new MqttChatEntityDao(mqttChatEntityDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(MqttChatEntity.class, mqttChatEntityDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        mqttChatEntityDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public MqttChatEntityDao getMqttChatEntityDao() {
        return mqttChatEntityDao;
    }

}
